# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required
language: r
warnings_are_errors: false
dist: trusty

r_packages:
  - testthat
  - covr

r_github_packages:
  - greta-dev/greta

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user 'tensorflow==1.14'
  - pip install --user 'tensorflow-probability==0.7.0'

after_success:
  - Rscript -e 'covr::codecov()'
